#[rustfmt::skip]
pub const ROTATIONS: [[Piece; 4]; 7] = [
    // I
    [
        Piece {
            shape: [[1, 1, 1, 1], 
                    [0, 0, 0, 0], 
                    [0, 0, 0, 0], 
                    [0, 0, 0, 0]],
            width: 4,
            height: 1,
            leftmost: [0, 0, 0, 0],
            rightmost: [3, 0, 0, 0],
        },
        Piece {
            shape: [[1, 0, 0, 0], 
                    [1, 0, 0, 0], 
                    [1, 0, 0, 0], 
                    [1, 0, 0, 0]],
            width: 1,
            height: 4,
            leftmost: [0, 0, 0, 0],
            rightmost: [0, 0, 0, 0],
        },
        Piece {
            shape: [[1, 1, 1, 1], 
                    [0, 0, 0, 0], 
                    [0, 0, 0, 0], 
                    [0, 0, 0, 0]],
            width: 4,
            height: 1,
            leftmost: [0, 0, 0, 0],
            rightmost: [3, 0, 0, 0],
        },
        Piece {
            shape: [[1, 0, 0, 0], 
                    [1, 0, 0, 0], 
                    [1, 0, 0, 0], 
                    [1, 0, 0, 0]],
            width: 1,
            height: 4,
            leftmost: [0, 0, 0, 0],
            rightmost: [0, 0, 0, 0],
        },
    ],
    // T
    [
        Piece {
            shape: [[1, 1, 1, 0], 
                    [0, 1, 0, 0], 
                    [0, 0, 0, 0], 
                    [0, 0, 0, 0]],
            width: 3,
            height: 2,
            leftmost: [0, 1, 0, 0],
            rightmost: [2, 1, 0, 0],
        },
        Piece {
            shape: [[1, 0, 0, 0], 
                    [1, 1, 0, 0], 
                    [1, 0, 0, 0], 
                    [0, 0, 0, 0]],
            width: 2,
            height: 3,
            leftmost: [0, 0, 0, 0],
            rightmost: [1, 0, 0, 0],
        },
        Piece {
            shape: [[0, 1, 0, 0], 
                    [1, 1, 1, 0], 
                    [0, 0, 0, 0], 
                    [0, 0, 0, 0]],
            width: 3,
            height: 2,
            leftmost: [1, 0, 0, 0],
            rightmost: [1, 2, 0, 0],
        },
        Piece {
            shape: [[0, 1, 0, 0], 
                    [1, 1, 0, 0], 
                    [0, 1, 0, 0], 
                    [0, 0, 0, 0]],
            width: 2,
            height: 3,
            leftmost: [0, 0, 0, 0],
            rightmost: [1, 1, 0, 0],
        },
    ],
    // O
    [
        Piece {
            shape: [[1, 1, 0, 0], 
                    [1, 1, 0, 0], 
                    [0, 0, 0, 0], 
                    [0, 0, 0, 0]],
            width: 2,
            height: 2,
            leftmost: [0, 0, 0, 0],
            rightmost: [1, 1, 0, 0],
        },
        Piece {
            shape: [[1, 1, 0, 0], 
                    [1, 1, 0, 0], 
                    [0, 0, 0, 0], 
                    [0, 0, 0, 0]],
            width: 2,
            height: 2,
            leftmost: [0, 0, 0, 0],
            rightmost: [1, 1, 0, 0],
        },
        Piece {
            shape: [[1, 1, 0, 0], 
                    [1, 1, 0, 0], 
                    [0, 0, 0, 0], 
                    [0, 0, 0, 0]],
            width: 2,
            height: 2,
            leftmost: [0, 0, 0, 0],
            rightmost: [1, 1, 0, 0],
        },
        Piece {
            shape: [[1, 1, 0, 0], 
                    [1, 1, 0, 0], 
                    [0, 0, 0, 0], 
                    [0, 0, 0, 0]],
            width: 2,
            height: 2,
            leftmost: [0, 0, 0, 0],
            rightmost: [1, 1, 0, 0],
        },
    ],
    // J
    [
        Piece {
            shape: [[1, 1, 1, 0], 
                    [1, 0, 0, 0], 
                    [0, 0, 0, 0], 
                    [0, 0, 0, 0]],
            width: 3,
            height: 2,
            leftmost: [0, 0, 0, 0],
            rightmost: [2, 0, 0, 0],
        },
        Piece {
            shape: [[1, 0, 0, 0], 
                    [1, 0, 0, 0], 
                    [1, 1, 0, 0], 
                    [0, 0, 0, 0]],
            width: 2,
            height: 3,
            leftmost: [0, 0, 0, 0],
            rightmost: [1, 1, 0, 0],
        },
        Piece {
            shape: [[0, 0, 1, 0], 
                    [1, 1, 1, 0], 
                    [0, 0, 0, 0], 
                    [0, 0, 0, 0]],
            width: 3,
            height: 2,
            leftmost: [2, 0, 0, 0],
            rightmost: [2, 2, 0, 0],
        },
        Piece {
            shape: [[1, 1, 0, 0], 
                    [0, 1, 0, 0], 
                    [0, 1, 0, 0], 
                    [0, 0, 0, 0]],
            width: 2,
            height: 3,
            leftmost: [0, 0, 0, 0],
            rightmost: [1, 1, 0, 0],
        },
    ],
    // L
    [
        Piece {
            shape: [[1, 1, 1, 0], 
                    [0, 0, 1, 0], 
                    [0, 0, 0, 0], 
                    [0, 0, 0, 0]],
            width: 3,
            height: 2,
            leftmost: [0, 0, 0, 0],
            rightmost: [2, 0, 0, 0],
        },
        Piece {
            shape: [[1, 1, 0, 0], 
                    [1, 0, 0, 0], 
                    [1, 0, 0, 0], 
                    [0, 0, 0, 0]],
            width: 2,
            height: 3,
            leftmost: [0, 0, 0, 0],
            rightmost: [1, 0, 0, 0],
        },
        Piece {
            shape: [[1, 0, 0, 0], 
                    [1, 1, 1, 0], 
                    [0, 0, 0, 0], 
                    [0, 0, 0, 0]],
            width: 3,
            height: 2,
            leftmost: [0, 0, 0, 0],
            rightmost: [2, 0, 0, 0],
        },
        Piece {
            shape: [[0, 1, 0, 0], 
                    [0, 1, 0, 0], 
                    [1, 1, 0, 0], 
                    [0, 0, 0, 0]],
            width: 2,
            height: 3,
            leftmost: [0, 0, 0, 0],
            rightmost: [1, 1, 0, 0],
        },
    ],
    // S
    [
        Piece {
            shape: [[1, 1, 0, 0], 
                    [0, 1, 1, 0], 
                    [0, 0, 0, 0], 
                    [0, 0, 0, 0]],
            width: 3,
            height: 2,
            leftmost: [0, 0, 0, 0],
            rightmost: [1, 2, 0, 0],
        },
        Piece {
            shape: [[0, 1, 0, 0], 
                    [1, 1, 0, 0], 
                    [1, 0, 0, 0], 
                    [0, 0, 0, 0]],
            width: 2,
            height: 3,
            leftmost: [0, 0, 0, 0],
            rightmost: [1, 1, 0, 0],
        },
        Piece {
            shape: [[1, 1, 0, 0], 
                    [0, 1, 1, 0], 
                    [0, 0, 0, 0], 
                    [0, 0, 0, 0]],
            width: 3,
            height: 2,
            leftmost: [0, 0, 0, 0],
            rightmost: [1, 2, 0, 0],
        },
        Piece {
            shape: [[0, 1, 0, 0], 
                    [1, 1, 0, 0], 
                    [1, 0, 0, 0], 
                    [0, 0, 0, 0]],
            width: 2,
            height: 3,
            leftmost: [0, 0, 0, 0],
            rightmost: [1, 1, 0, 0],
        },
    ],
    // Z
    [
        Piece {
            shape: [[0, 1, 1, 0], 
                    [1, 1, 0, 0], 
                    [0, 0, 0, 0], 
                    [0, 0, 0, 0]],
            width: 3,
            height: 2,
            leftmost: [1, 0, 0, 0],
            rightmost: [2, 1, 0, 0],
        },
        Piece {
            shape: [[1, 0, 0, 0], 
                    [1, 1, 0, 0], 
                    [0, 1, 0, 0], 
                    [0, 0, 0, 0]],
            width: 2,
            height: 3,
            leftmost: [0, 0, 0, 0],
            rightmost: [0, 1, 0, 0],
        },
        Piece {
            shape: [[0, 1, 1, 0], 
                    [1, 1, 0, 0], 
                    [0, 0, 0, 0], 
                    [0, 0, 0, 0]],
            width: 3,
            height: 2,
            leftmost: [1, 0, 0, 0],
            rightmost: [2, 1, 0, 0],
        },
        Piece {
            shape: [[1, 0, 0, 0], 
                    [1, 1, 0, 0], 
                    [0, 1, 0, 0], 
                    [0, 0, 0, 0]],
            width: 2,
            height: 3,
            leftmost: [0, 0, 0, 0],
            rightmost: [0, 1, 0, 0],
        },
    ],
];

#[derive(Debug, Clone, Copy)]
pub struct Piece {
    pub shape: [[u8; 4]; 4],
    pub width: usize,
    pub height: usize,
    pub leftmost: [i32; 4],
    pub rightmost: [i32; 4],
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum PieceType {
    I = 0,
    T = 1,
    O = 2,
    J = 3,
    L = 4,
    S = 5,
    Z = 6,
}
